[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/kilavuz"
  to = "/kilavuz.html"
  status = 200

[[redirects]]
  from = "/ek-:no"
  to = "/ek/ek-:no.html"
  status = 200
